# Generated by Django 4.2.20 on 2025-04-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_information_tickets_informationvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
