# Generated by Django 4.2.20 on 2025-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
    ]
