# Generated by Django 4.2.18 on 2025-02-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_news_country_post_country_skill_country_tool_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post-images/'),
        ),
    ]
