# Generated by Django 4.2.18 on 2025-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(default='ananoymous', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='country',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
