# Generated by Django 4.2.18 on 2025-02-08 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0004_servicerequest_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.CreateModel(
            name='ServiceResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='in_progress', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='service.servicerequest')),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
    ]
