"""
Django settings for bmp project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6!qhlht*os^zn+elk*wd2(6_5cu(4si2k)xcrho8^rrgj-rc_@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['b578-102-0-0-244.ngrok-free.app', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = [
    'https://b578-102-0-0-244.ngrok-free.app',
    'http://localhost',
    'http://127.0.0.1'
]



# Application definition

INSTALLED_APPS = [
     # ASGI server for WebSockets

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',  # Optional, for social logins
    'crispy_forms',
    'crispy_bootstrap5',

    'base',
    'custom_account',
    'dashboard',
    'chat',
    'agents',
    'freelance',
    'partner',
    'payment',
    'service',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'bmp.urls'
ASGI_APPLICATION = "bmp.asgi.application"  # Change 'bmp' to your project name




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'bmp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#DATABASES = {
   # 'default': {
     #   'ENGINE': 'django.db.backends.postgresql',
#  'NAME': 'bmsbmp',
#    'USER': 'postgres',
#    'PASSWORD': 'covid@2019',
#      'HOST': 'localhost',  # Change if using a remote DB
#       'PORT': '5432',  # Default PostgreSQL port
#  }
# }
ACCOUNT_FORMS = {
    'signup': 'custom_account.forms.DefaultUserSignupForm',  # Change this to your actual module path
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]
AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',  # First priority
    'django.contrib.auth.backends.ModelBackend',  # Second priority
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_TEMPLATE_PACK = "bootstrap5"

SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_PROVIDERS = {
     'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'github': {
        'APP': {
            'client_id': 'Ov23li5UIYdHimIcSs0W',
            'secret': '7355816b2c5dcad56bcb91967788b312c3e4b4d1',
            'key': ''
        }
    }
}

AUTH_USER_MODEL = 'custom_account.CustomUser'

SITE_ID = 1

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
SOCIALACCOUNT_ADAPTER = 'custom_account.adapters.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'custom_account.adapters.CustomAccountAdapter'
ACCOUNT_FORMS = {'signup': 'custom_account.forms.CustomUserSignupForm'}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ACCOUNT_SIGNUP_FORM_CLASS = 'custom_account.forms.DefaultUserSignupForm'
LOGIN_REDIRECT_URL = 'custom_account:redirect_after_login'  # Route to this view after login
LOGOUT_REDIRECT_URL = 'base:index'
ACCOUNT_EMAIL_REQUIRED = True

SOCIALACCOUNT_QUERY_EMAIL = True

ACCOUNT_SESSION_REMEMBER = True
# ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

  # Use SMTP to send emails
EMAIL_HOST = 'smtp.gmail.com'  # Gmail's SMTP server
EMAIL_PORT = 587  # SMTP port for Gmail
EMAIL_USE_TLS = True  # Use TLS for security
EMAIL_HOST_USER = 'bmsbmp236@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'wxjp prht jjnr noex'  # App password if using 2FA
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Email address used as the sender









# settings.py

