# Generated by Django 4.2.20 on 2025-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default='d94afa3537', editable=False, max_length=32, unique=True),
        ),
    ]
