# Generated by Django 4.2.20 on 2025-03-28 21:46

import custom_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0004_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=custom_account.models.generate_referral_code, editable=False, max_length=32, unique=True),
        ),
    ]
